# Generated by Django 5.0.4 on 2025-10-31 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_name_manual',
            field=models.CharField(blank=True, help_text='Captured company name when no linked company exists', max_length=200),
        ),
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.company'),
        ),
    ]
