# Generated by Django 5.0.4 on 2025-11-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contact_company_name_manual_deal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, help_text='Last time contact was engaged', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='time_spent_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours spent on this deal/project', max_digits=8),
        ),
        migrations.AddField(
            model_name='deal',
            name='timer_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
