# Generated by Django 5.0.4 on 2025-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contact_last_contact_date_deal_time_spent_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('sport', 'FINISHER SPORT')], default='sport', max_length=20),
        ),
    ]
