# Generated by Django 5.0.4 on 2025-11-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_userprofile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('user', 'Standard User')], default='user', max_length=20),
        ),
    ]
