# Generated by Django 5.0.4 on 2025-11-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_is_self_employed_company_direct_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.TextField(blank=True, help_text="Reason for ban (e.g., 'Unpaid subscription', 'Terms violation')"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Ban user if unpaid or violation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Most recent login IP address', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('trial', 'Trial Period')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used during registration', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='14-day trial period end date', null=True),
        ),
    ]
