# Generated by Django 5.0.4 on 2025-11-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_userprofile_ban_reason_userprofile_banned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('registration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_reason', models.TextField(blank=True, help_text='Why was this user deleted?')),
                ('contact_count', models.IntegerField(default=0)),
                ('company_count', models.IntegerField(default=0)),
                ('deal_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Deleted User Log',
                'verbose_name_plural': 'Deleted User Logs',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
