# Generated by ChatGPT on 2025-11-03
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_rename_crm_notific_recipient_created_idx_crm_notific_recipie_a36144_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requires_password_reset',
            field=models.BooleanField(default=False, help_text='Force user to change password at next login'),
        ),
    ]
