# Generated by ChatGPT on 2025-11-03
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_userprofile_requires_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('support', 'Support'), ('bug', 'Bug'), ('feature', 'Feature Request'), ('task', 'Task')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('support', 'Support'), ('operations', 'Operations')], default='support', max_length=30),
        ),
    ]
