# Generated by Django 6.0.1 on 2026-03-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_ticket_fields_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-5', '1-5 employees'), ('6-20', '6-20 employees'), ('21-50', '21-50 employees'), ('51-200', '51-200 employees'), ('200+', '200+ employees')], help_text='Number of employees', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('ZA', 'South Africa'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('Other', 'Other')], default='ZA', help_text='Country/Region', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_crm',
            field=models.CharField(blank=True, help_text='Current CRM system (if migrating)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expected_contacts',
            field=models.CharField(blank=True, choices=[('0-100', '0-100 contacts'), ('100-500', '100-500 contacts'), ('500-2000', '500-2000 contacts'), ('2000+', '2000+ contacts')], help_text='Expected number of contacts', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('it', 'Information Technology'), ('retail', 'Retail & E-commerce'), ('healthcare', 'Healthcare & Medical'), ('manufacturing', 'Manufacturing'), ('finance', 'Finance & Banking'), ('real_estate', 'Real Estate'), ('education', 'Education & Training'), ('hospitality', 'Hospitality & Tourism'), ('construction', 'Construction & Engineering'), ('consulting', 'Consulting & Professional Services'), ('marketing', 'Marketing & Advertising'), ('logistics', 'Logistics & Transportation'), ('other', 'Other')], help_text='Industry/Business type', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intended_use_case',
            field=models.TextField(blank=True, help_text="Why do you need a CRM? What's your use case?"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='User agreed to receive marketing communications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('google', 'Google Search'), ('social_media', 'Social Media'), ('referral', 'Friend/Colleague Referral'), ('advertisement', 'Advertisement'), ('blog', 'Blog/Article'), ('event', 'Event/Conference'), ('other', 'Other')], help_text='How did you hear about us?', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted Terms & Conditions', null=True),
        ),
    ]
