# Generated by Django 5.0.4 on 2026-03-04 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_employeeaddotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('it_equipment', 'IT Equipment'), ('office_furniture', 'Office Furniture'), ('vehicles', 'Vehicles'), ('machinery', 'Machinery & Tools'), ('property', 'Property & Buildings'), ('software', 'Software Licenses'), ('communication', 'Communication Devices'), ('other', 'Other Assets')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('company_name', models.CharField(help_text='Company this category belongs to', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['company_name', 'name'],
                'unique_together': {('name', 'company_name')},
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company_name', models.CharField(help_text='Company this division belongs to', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Division manager/head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_divisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name', 'name'],
                'unique_together': {('name', 'company_name')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Organizational division/department (ADMP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.division'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text='Unique asset identifier/tag', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Asset name/description', max_length=200)),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer serial number', max_length=200)),
                ('model', models.CharField(blank=True, help_text='Model number/name', max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase cost', max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value', max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active/In Use'), ('available', 'Available'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired/Disposed'), ('lost', 'Lost/Stolen')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical location (building/room/desk)', max_length=300)),
                ('company_name', models.CharField(help_text='Company that owns this asset', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes, maintenance history, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee this asset is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='crm.assetcategory')),
                ('division', models.ForeignKey(blank=True, help_text='Division this asset belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='crm.division')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name', 'status'], name='crm_asset_company_b5c71f_idx'), models.Index(fields=['assigned_to'], name='crm_asset_assigne_59b558_idx'), models.Index(fields=['asset_tag'], name='crm_asset_asset_t_149e01_idx')],
            },
        ),
    ]
