# Generated by Django 5.0.4 on 2026-03-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_assetcategory_division_userprofile_division_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_offboarded',
            field=models.BooleanField(default=False, help_text='Whether this employee has been offboarded'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='offboarded_at',
            field=models.DateTimeField(blank=True, help_text='When this employee was offboarded', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, help_text='When this employee was onboarded', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, help_text='Who onboarded this employee into the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_onboarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='Direct supervisor/manager this employee reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'CEO / Administrator'), ('executive', 'Executive'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('user', 'Standard Employee')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='OffboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_email', models.EmailField(max_length=254)),
                ('requested_by_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('reason', models.TextField(help_text='Reason for offboarding this employee')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='System admin notes on the decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Employee to be offboarded', on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='System admin who processed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='CEO/Executive who requested offboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offboarding Request',
                'verbose_name_plural': 'Offboarding Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text='Stored name (persists after deletion)', max_length=200)),
                ('employee_email', models.EmailField(help_text='Stored email (persists after deletion)', max_length=254)),
                ('action', models.CharField(choices=[('onboard', 'Onboarded'), ('offboard', 'Offboarded')], max_length=20)),
                ('performed_by_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('role_assigned', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Reason for offboarding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='The employee that was onboarded/offboarded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_history', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(help_text='Who performed the onboarding/offboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Log',
                'verbose_name_plural': 'Onboarding Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
