# Generated by Django 6.0.1 on 2026-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_userprofile_mfa_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_code',
            field=models.CharField(blank=True, help_text='Current OTP code (6 digits)', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_code_attempts',
            field=models.IntegerField(default=0, help_text='Failed MFA attempts counter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_code_created_at',
            field=models.DateTimeField(blank=True, help_text='When the OTP code was generated', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=True, help_text='Whether MFA is enabled for this user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, help_text='Last successful MFA verification time', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('luxury', 'FINISHER LUXURY')], default='luxury', max_length=20),
        ),
    ]
