# Generated by Django 6.0.1 on 2026-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_userprofile_mfa_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_type',
            field=models.CharField(choices=[('company', 'Company / Organization'), ('individual', 'Individual / Sole Proprietor')], default='company', help_text='Client type: Organization or Individual', max_length=20),
        ),
    ]
