# Generated by Copilot assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_company_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, help_text='When the user last changed their password'),
        ),
    ]
