# Generated by Django 5.0.4 on 2026-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_add_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='billing_type',
            field=models.CharField(choices=[('standard', 'Standard (one-off)'), ('recurring', 'Recurring (subscription)')], default='standard', help_text='Billing type for the product', max_length=30),
        ),
    ]
