# Generated by Django 5.0.4 on 2026-04-01 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_product_billing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('send_email', 'Send Email'), ('send_whatsapp', 'Send WhatsApp'), ('create_task', 'Create Task/Ticket'), ('notify_user', 'Send Notification'), ('change_stage', 'Change Deal Stage'), ('assign_user', 'Assign To User'), ('add_note', 'Add Note/Activity'), ('wait', 'Wait (Delay)')], max_length=20),
        ),
        migrations.CreateModel(
            name='WebsiteLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('contact_form', 'Contact Form'), ('chat_widget', 'Chat Widget')], default='contact_form', max_length=20)),
                ('inbound_message', models.TextField(blank=True)),
                ('inbound_received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_status', models.CharField(choices=[('new', 'New'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('call_notes', models.TextField(blank=True)),
                ('meeting_status', models.CharField(choices=[('none', 'No Meeting'), ('proposed', 'Proposed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='none', max_length=20)),
                ('meeting_datetime', models.DateTimeField(blank=True, null=True)),
                ('meeting_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_lead', to='crm.contact')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_website_leads', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inbound_received_at'],
                'indexes': [models.Index(fields=['owner', '-inbound_received_at'], name='crm_website_owner_i_259578_idx'), models.Index(fields=['response_status', 'meeting_status'], name='crm_website_respons_d84c59_idx')],
            },
        ),
    ]
