# Generated by Django

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_alter_workflowaction_action_type_websitelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelead',
            name='spam_score',
            field=models.IntegerField(default=0, help_text='Automated lead quality score'),
        ),
        migrations.AddField(
            model_name='websitelead',
            name='is_spam_risk',
            field=models.BooleanField(default=False, help_text='Flagged by Bullshit Filter'),
        ),
    ]