# Generated by Django

from django.db import migrations

def scrub_ghost_contacts(apps, schema_editor):
    WebsiteLead = apps.get_model('crm', 'WebsiteLead')
    
    # All website leads that haven't been officially promoted
    # but still have a Contact linked (the old logic flaw that polluted the CRM)
    ghost_leads = WebsiteLead.objects.filter(contact__isnull=False).exclude(response_status='promoted')
    
    for lead in ghost_leads:
        # 1. Back up contact details into the lead itself just in case
        if not lead.first_name:
            lead.first_name = lead.contact.first_name
        if not lead.last_name:
            lead.last_name = lead.contact.last_name
        if not lead.email:
            lead.email = lead.contact.email
        if not lead.phone:
            lead.phone = lead.contact.phone
        lead.save()

        # 2. Obliterate the ghost Contact
        # Because WebsiteLead.contact is SET_NULL, this safely unlinks it
        # and removes it from the actual "Clients" tab.
        lead.contact.delete()

class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0028_websitelead_spam_fields'),
    ]
    operations = [
        migrations.RunPython(scrub_ghost_contacts),
    ]