# Generated by Django

from django.db import migrations, models
import django.db.models.deletion

def copy_contact_data_to_lead(apps, schema_editor):
    WebsiteLead = apps.get_model('crm', 'WebsiteLead')
    for lead in WebsiteLead.objects.all():
        if lead.contact:
            lead.first_name = lead.contact.first_name
            lead.last_name = lead.contact.last_name
            lead.email = lead.contact.email
            lead.phone = lead.contact.phone
            lead.save()

def delete_unpromoted_contacts(apps, schema_editor):
    WebsiteLead = apps.get_model('crm', 'WebsiteLead')
    # Find all leads that are NOT promoted to deals yet
    unpromoted_leads = WebsiteLead.objects.exclude(response_status='promoted')
    for lead in unpromoted_leads:
        if lead.contact:
            contact = lead.contact
            # Unlink the contact so deleting it doesn't delete the lead
            lead.contact = None
            lead.save()
            # SCRUB: Delete the fake client profile to clean the Clients tab
            contact.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_websitelead_spam_fields'),
    ]

    operations = [
        migrations.AddField(model_name='websitelead', name='email', field=models.EmailField(blank=True, max_length=254)),
        migrations.AddField(model_name='websitelead', name='first_name', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='websitelead', name='last_name', field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='websitelead', name='phone', field=models.CharField(blank=True, max_length=20)),
        migrations.AlterField(
            model_name='websitelead',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_lead', to='crm.contact'),
        ),
        # 1. Copy data so we don't lose emails/names
        migrations.RunPython(copy_contact_data_to_lead),
        
        # 2. Run the Great Scrub! (Delete junk from Clients tab)
        migrations.RunPython(delete_unpromoted_contacts),
    ]