# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_scrub_ghost_contacts'),
        ('crm', '0029_websitelead_ghost_fields'),
    ]

    operations = []