# Generated by Django 5.0.4 on 2026-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_merge_0029_scrub_ghost_contacts_and_0029_websitelead_ghost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelead',
            name='response_status',
            field=models.CharField(choices=[('new', 'New'), ('responded', 'Responded'), ('promoted', 'Promoted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
