# Generated by Django 6.1.1 on 2026-09-04 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_trial_duration_7_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Official corporate work email', max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('job_title', models.CharField(help_text='Executive designation (e.g. CEO, MD, VP)', max_length=120)),
                ('is_ceo', models.BooleanField(default=True, help_text='Whether applicant is the CEO / Principal Officer')),
                ('executive_sponsor_name', models.CharField(blank=True, help_text='Executive Sponsor if not CEO', max_length=150)),
                ('executive_sponsor_email', models.EmailField(blank=True, help_text='Executive Sponsor Email', max_length=254)),
                ('hashed_password', models.CharField(help_text='Securely hashed password for instant provisioning', max_length=256)),
                ('company_name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, default='consulting', max_length=100)),
                ('physical_address', models.TextField(help_text='Building, Street Address')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(default='Gauteng', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('postal_address', models.TextField(blank=True, help_text='Postal box or delivery address')),
                ('cipc_number', models.CharField(blank=True, help_text='CIPC Registration Number', max_length=50)),
                ('tax_number', models.CharField(blank=True, help_text='SARS Tax / VAT Number', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Executive Review'), ('approved', 'Approved & Provisioned'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporate Access Request',
                'verbose_name_plural': 'Corporate Access Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='securityaudittrail',
            new_name='crm_securit_event_t_1414dd_idx',
            old_name='crm_sec_ev_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='securityaudittrail',
            new_name='crm_securit_ip_addr_0991e7_idx',
            old_name='crm_sec_ip_ts_idx',
        ),
        migrations.AlterField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_companies', to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_code',
            field=models.CharField(blank=True, help_text='Current OTP code (6 digits - legacy)', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_code_hash',
            field=models.CharField(blank=True, help_text='Salted SHA-256 hash of active OTP', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_salt',
            field=models.CharField(blank=True, help_text='Cryptographic salt for OTP', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='7-day trial period end date', null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='corporateaccessrequest',
            name='created_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_access_requests', to='crm.organization'),
        ),
        migrations.AddField(
            model_name='corporateaccessrequest',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporateaccessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
