# Generated by Django 6.1.1 on 2026-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_decouple_adminluxury_scrub_mtamboholdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateaccessrequest',
            name='requested_tier',
            field=models.CharField(default='luxury', help_text='Plan chosen by applicant: basic, luxury, executive, enterprise', max_length=50),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=999.0, help_text='Monthly subscription rate in ZAR', max_digits=10),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='notes',
            field=models.TextField(blank=True, help_text='Private CEO sales notes'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='payment_method',
            field=models.CharField(default='payfast', help_text='payfast, capitec, eft, cash', max_length=50),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Bank reference or PayFast subscription ID', max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Luxury Basic'), ('luxury', 'Luxury Team'), ('executive', 'Executive Suite'), ('enterprise', 'Enterprise Custom'), ('trial', '7-Day VIP Trial')], default='luxury', max_length=50),
        ),
    ]
