# Generated by Django 6.1.1 on 2026-09-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_corporateaccessrequest_requested_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Client company linked to ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.company'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Client contact linked to ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_sale_initiated',
            field=models.BooleanField(default=False, help_text='Whether ticket initiates a commercial sale / license issue'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product or license to sell', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.product'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Units or licenses to sell'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sale_status',
            field=models.CharField(choices=[('none', 'No Sale Attached'), ('pending', 'Quotation / Pending Sale'), ('invoiced', 'License Issued / Invoiced'), ('paid', 'Paid & Closed'), ('cancelled', 'Cancelled')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total calculated sale / license value', max_digits=12),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price in ZAR', max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_assets',
            field=models.BooleanField(default=False, help_text='Delegated permission: manager can add and manage company physical assets'),
        ),
    ]
