# Generated by Django 6.1.1 on 2026-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_ticket_company_ticket_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='can_export_csv',
            field=models.BooleanField(default=False, help_text='Anti-theft data lock: False during trial, True for paid'),
        ),
        migrations.AddField(
            model_name='organization',
            name='lead_limit',
            field=models.PositiveIntegerField(default=50, help_text='Maximum lead intake limit during trial period'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=2, help_text='Maximum active user seats for organization (2 on trial)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Luxury Basic'), ('luxury', 'Luxury Team'), ('executive', 'Executive Suite'), ('enterprise', 'Enterprise Custom'), ('trial', '15-Day VIP Trial')], default='trial', max_length=50),
        ),
    ]
