# Generated by Django 6.1.1 on 2026-09-18 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_organization_can_export_csv_organization_lead_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='15-day trial period end date', null=True),
        ),
        migrations.CreateModel(
            name='TenantIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('facebook', 'Meta / Facebook Lead Ads'), ('gmail', 'Google Workspace / Gmail'), ('outlook', 'Microsoft 365 / Outlook'), ('whatsapp', 'WhatsApp Business API'), ('payfast', 'PayFast Payment Gateway')], db_index=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Encrypted provider credentials and settings')),
                ('total_events_ingested', models.PositiveIntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Tenant organization that owns this integration', on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='crm.organization')),
            ],
            options={
                'verbose_name': 'Tenant Integration',
                'verbose_name_plural': 'Tenant Integrations',
                'ordering': ['provider'],
                'unique_together': {('organization', 'provider')},
            },
        ),
    ]
