# Generated by Django 6.1.1 on 2026-09-18 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_alter_userprofile_trial_ends_at_tenantintegration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EulaAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='v1.0-2026', help_text='Active legal version of EULA', max_length=30)),
                ('signer_full_name', models.CharField(help_text='Legal name of authorized signatory', max_length=200)),
                ('signer_email', models.EmailField(help_text='Corporate email of signatory', max_length=254)),
                ('signer_title', models.CharField(default='Authorized Officer', help_text='Signatory capacity/title (e.g. CEO, Director)', max_length=100)),
                ('certificate_id', models.CharField(db_index=True, help_text='Cryptographic certificate identifier', max_length=80, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Signer IP address at execution time', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Signer client user agent')),
                ('pdf_filename', models.CharField(blank=True, help_text='Filename of generated certificate PDF', max_length=255)),
                ('pdf_document', models.FileField(blank=True, help_text='Permanent PDF certificate file', null=True, upload_to='eula_certificates/')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(help_text='Tenant enterprise that accepted the license agreement', on_delete=django.db.models.deletion.CASCADE, related_name='eula_acceptances', to='crm.organization')),
                ('user', models.ForeignKey(help_text='User/Director who digitally executed the agreement', on_delete=django.db.models.deletion.CASCADE, related_name='eula_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EULA Acceptance Audit Record',
                'verbose_name_plural': 'EULA Acceptance Audit Records',
                'ordering': ['-accepted_at'],
                'unique_together': {('organization', 'version')},
            },
        ),
    ]
