# Generated by Django 6.1.1 on 2026-09-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_eulaacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_logo',
            field=models.ImageField(blank=True, help_text='Custom company logo for white-label quotes/invoices', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_white_labeled',
            field=models.BooleanField(default=False, help_text='True if R199/mo white-label is active (removes Finisher watermark)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tender_pack_unlocked',
            field=models.BooleanField(default=False, help_text='True if R350 once-off tender & funding pack has been unlocked'),
        ),
        migrations.AddField(
            model_name='organization',
            name='white_label_subscription_id',
            field=models.CharField(blank=True, help_text='PayFast recurring subscription ID for white-label', max_length=120),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=5, help_text='Maximum active user seats for organization (5 on Sovereign tier)'),
        ),
    ]
