# Generated by Django 6.1.1 on 2026-09-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_organization_custom_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Corporate Sovereign'), ('luxury', 'Luxury Team'), ('executive', 'Executive Suite'), ('enterprise', 'Enterprise Custom')], default='basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trial', 'Legacy Trial')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('trial', 'Legacy Trial')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Legacy trial end date (no longer used)', null=True),
        ),
    ]
