# Generated by Django 6.1.1 on 2026-09-19
from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def unlock_all_organizations(apps, schema_editor):
    Organization = apps.get_model('crm', 'Organization')
    OrganizationSubscription = apps.get_model('crm', 'OrganizationSubscription')
    UserProfile = apps.get_model('crm', 'UserProfile')

    far_future = timezone.now() + timedelta(days=3650)  # 10-year permanent allocation

    # 1. Permanently unlock all organizations to Corporate Sovereign with 6,000 lead capacity
    Organization.objects.all().update(
        subscription_tier='basic',
        is_active=True,
        can_export_csv=True,
        lead_limit=6000,
        trial_end_date=far_future
    )

    # 2. Update all subscriptions to active
    OrganizationSubscription.objects.filter(status='trial').update(status='active')

    # 3. Update all user profiles to paid & unbanned
    UserProfile.objects.filter(payment_status__in=['trial', 'pending']).update(payment_status='paid')
    UserProfile.objects.filter(is_banned=True, ban_reason__icontains='trial').update(
        is_banned=False,
        ban_reason='',
        banned_at=None
    )

def reverse_unlock(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_alter_organization_subscription_tier_and_more'),
    ]

    operations = [
        migrations.RunPython(unlock_all_organizations, reverse_unlock),
    ]
