# Generated by Django 6.1.1 on 2026-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_permanently_unlock_all_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when last reminder email or alert was dispatched', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reminders dispatched for this ticket'),
        ),
    ]
