# Generated by Django 6.1.1 on 2026-09-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_ticket_last_reminder_sent_at_ticket_reminder_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tender_pack_unlocked',
        ),
    ]
