# Generated by Django 6.1.1 on 2026-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_delete_adminluxury_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityaudittrail',
            name='event_type',
            field=models.CharField(choices=[('AUTH_LOGIN_SUCCESS', 'Login Success'), ('AUTH_LOGIN_FAILED', 'Login Failed'), ('AUTH_LOGOUT', 'Logout'), ('MFA_CHALLENGE', 'MFA Verification Challenge'), ('MFA_VERIFIED', 'MFA Verification Success'), ('AUTH_REGISTRATION', 'Registration Attempt'), ('AUTH_APPROVAL', 'Login / Access Approval'), ('EMPLOYEE_ONBOARDED', 'Employee Onboarded'), ('SECURITY_WARNING', 'Security Warning'), ('DATA_EXPORT', 'POPIA Data Export (CSV/PDF)'), ('DATA_DELETE', 'Record Deletion / Purge'), ('PRIVILEGE_CHANGE', 'User Role / Plan Mutation'), ('REGISTRATION_INCOMPLETE', 'Incomplete / Abandoned Registration'), ('SECURITY_POLICY_VIOLATION', 'Security Policy Violation')], db_index=True, max_length=50),
        ),
    ]
