const saCompanies = [
  'Absa Group Limited',
  'African Rainbow Minerals',
  'Aspen Pharmacare Holdings',
  'Barloworld Limited',
  'Bidvest Group',
  'Clicks Group',
  'Discovery Limited',
  'Distell Group Holdings',
  'FirstRand Limited',
  'Foschini Group',
  'Gold Fields Limited',
  'Hollard Insurance',
  'Impala Platinum Holdings',
  'Liberty Holdings',
  'Life Healthcare Group',
  'Massmart Holdings',
  'Momentum Metropolitan Holdings',
  'MTN Group',
  'Naspers Limited',
  'Nedbank Group',
  'Old Mutual Limited',
  'Pepkor Holdings',
  'Pick n Pay Stores',
  'Remgro Limited',
  'Sanlam Limited',
  'Sasol Limited',
  'Shoprite Holdings',
  'Sibanye-Stillwater',
  'Standard Bank Group',
  'Telkom SA SOC',
  'Tiger Brands',
  'Transnet SOC',
  'Vodacom Group',
  'Woolworths Holdings'
]

export default saCompanies
